development:
  adapter: postgresql
  database: <%= Settings.postgres.database %>
  encoding: unicode
  pool: <%= Settings.postgres.pool %>
  timeout: 5000
  username: <%= Settings.postgres.username %>
  password: <%= Settings.postgres.password %>
  host: <%= Settings.postgres.host %>
  port: <%= Settings.postgres.port %>
  sslmode: <%= Settings.postgres.sslmode %>

production:
  adapter: postgresql
  database: <%= Settings.postgres.database %>
  encoding: unicode
  pool: <%= Settings.postgres.pool %>
  timeout: 5000
  username: <%= Settings.postgres.username %>
  password: <%= Settings.postgres.password %>
  host: <%= Settings.postgres.host %>
  port: <%= Settings.postgres.port %>
  sslmode: <%= Settings.postgres.sslmode %>

test:
  adapter: sqlite3
  encoding: utf8
  database: 'db/test.sqlite3'
  pool: <%= Settings.test_sqlite.pool %>

# The places where these settings are filled out are settings.yml and production.yml
# You should only be filling in custom values and secrets within production.local.yml

edodb:
  adapter: <%= Settings.edodb.adapter %>
  host: <%=Settings.edodb.host %>
  port: <%=Settings.edodb.port %>
  database: <%=Settings.edodb.database %>
  username: <%=Settings.edodb.username %>
  password: <%=Settings.edodb.password %>
  pool: <%=Settings.edodb.pool %>
  timeout: <%=Settings.edodb.timeout %>

edwdb:
  adapter: <%= Settings.edwdb.adapter %>
  host: <%=Settings.edwdb.host %>
  port: <%=Settings.edwdb.port %>
  database: <%=Settings.edwdb.database %>
  username: <%=Settings.edwdb.username %>
  password: <%=Settings.edwdb.password %>
  pool: <%=Settings.edwdb.pool %>
  timeout: <%=Settings.edwdb.timeout %>
