application:
  layer: "development"

logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || true %>
  slow_query_threshold_in_ms: 2000

cache:
  store: "memory"
  log_level: <%= Logger::DEBUG %>

canvas_proxy:
  fake: true

cas_server: 'https://auth-test.berkeley.edu/cas'

cas_logout_url: 'https://auth-test.berkeley.edu/cas/logout'

google_proxy:
  fake: true

mailgun_proxy:
  fake: true

cal1card_proxy:
  fake: true

webcast_proxy:
  fake: true

postgres:
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] || 'calcentral_development' %>
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] || 'calcentral_development' %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] || 'secret' %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>
  pool: 3

campusdb:
  fake: true

edodb:
  fake: true

hub_term_proxy:
  fake: true

features:
  cal1card: true
  course_manage_official_sections: true
  reauthentication: false
  videos: true
